package OOP;
//iman

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class CustomerLogin extends javax.swing.JFrame {
Connection con = null; //set connection reference to null
ResultSet rs = null;
PreparedStatement pst = null;


    public CustomerLogin() {
        initComponents();
        con=dbConnection.con();
         this.setLocationRelativeTo(null); //set frame center screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton4 = new Project.MyButton();
        myButton1 = new Project.MyButton();
        jLabel2 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPass = new javax.swing.JPasswordField();
        myButton2 = new Project.MyButton();
        ckbox = new javax.swing.JCheckBox();
        myButton3 = new Project.MyButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton4.setText("SIGN UP");
        myButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myButton4MouseClicked(evt);
            }
        });
        myButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 550, 80, 30));

        myButton1.setText("LOGIN");
        myButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myButton1MouseClicked(evt);
            }
        });
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 550, 80, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 110, 50));
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 340, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 110, 50));
        getContentPane().add(jPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 340, 40));

        myButton2.setText("FORGOT PASSWORD");
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 170, 30));

        ckbox.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbox.setText("View Password");
        ckbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ckboxMouseClicked(evt);
            }
        });
        getContentPane().add(ckbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, -1, -1));

        myButton3.setText("BACK");
        myButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                myButton3MouseClicked(evt);
            }
        });
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/customerlogin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 950, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton1MouseClicked
       
    }//GEN-LAST:event_myButton1MouseClicked

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
        //Customer login 
        String username = jUsername.getText(); //username field
        String ps = jPass.getText();  //password field
        

        try{
            Statement st = con.createStatement();
            
            rs =st.executeQuery ("SELECT * FROM customerregister WHERE username='"+username+"' AND password='"+ps+"' "); //check from database = with input
        

            if(rs.next()){
                JOptionPane.showMessageDialog(rootPane, "Your Succefully Login ...."); //same data, succes login
                new UserHome(username).setVisible(true); //pass username to page
                this.setVisible(false);
               

            }else{
                JOptionPane.showMessageDialog(rootPane, "Wrong Password or Username. Please Try Again...."); //wrong data

            }
        }catch (SQLException ex) {
            Logger.getLogger(LoginForAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
  
    }//GEN-LAST:event_myButton1ActionPerformed

    private void ckboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ckboxMouseClicked
        
        //view  password
       
        if(ckbox.isSelected()){
            jPass.setEchoChar((char)0);
        }
        else
        {
            jPass.setEchoChar('*');
        }
       
    }//GEN-LAST:event_ckboxMouseClicked

    private void myButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton4MouseClicked
    this.setVisible(false);
        new CustomerSignUp().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_myButton4MouseClicked

    private void myButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton4ActionPerformed

    private void myButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_myButton3MouseClicked
    this.setVisible(false);
    new Welcome().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_myButton3MouseClicked

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
    this.setVisible(true);
    new CustomerForgotPassword().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ckbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPass;
    private javax.swing.JTextField jUsername;
    private Project.MyButton myButton1;
    private Project.MyButton myButton2;
    private Project.MyButton myButton3;
    private Project.MyButton myButton4;
    // End of variables declaration//GEN-END:variables
}
