package OOP;
//iman

import java.awt.HeadlessException;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class CustomerForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form CustomerForgotPassword
     */
    public CustomerForgotPassword() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myButton3 = new Project.MyButton();
        myButton2 = new Project.MyButton();
        myButton1 = new Project.MyButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        checkbox = new javax.swing.JCheckBox();
        jPassword = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myButton3.setText("BACK");
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 90, 40));

        myButton2.setText("SAVE");
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 90, 40));

        myButton1.setText("SEARCH");
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 90, 30));

        jLabel6.setText("New Password");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 130, -1));
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 200, 30));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 200, 30));

        jLabel5.setText("Answer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 120, -1));

        checkbox.setText("Show Password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 150, -1));
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 30));

        jLabel4.setText("Security Question");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, -1));
        getContentPane().add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 200, 30));

        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 80, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("FORGOT PASSWORD");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 40));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
    
        //view password
        if(checkbox.isSelected()){
            jPassword.setEchoChar((char)0);
        }
        else
        {
            jPassword.setEchoChar('*');
        }       
    }//GEN-LAST:event_checkboxActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
    String un = jUsername.getText(); //get username
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver"); //driver connector
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root",""); //connect with table
            Statement st = con.createStatement(); //create Statement
            ResultSet rs = st.executeQuery("select securityQ from customerregister where username ='"+un+"'"); //take data from database
            
            
            if(rs.next()) //move pointer to next row
            {
                jTextField11.setText(rs.getString(1));
            }
            else{
                JOptionPane.showMessageDialog(null, "Please write correct Username");
                con.close(); //close connection
                rs.close(); //close open ResultSet
            }
            
        }catch (ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(null, e); 
        }       
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
        
        //Customer forgot password
        String un = jUsername.getText();
        String newPassword = jPassword.getText();
        String securityQ = jTextField11.getText();
        String answer = jTextField3.getText();
        try{
            Class.forName("com.mysql.cj.jdbc.Driver"); //driver coonector
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root",""); //connect with table
            Statement st = con.createStatement(); //send SQL query to database
            ResultSet rs = st.executeQuery("select *from customerregister where username ='"+un+"' and answer='"+answer+"'"); //take data from table
           
            if(rs.next())
            {
               st.executeUpdate("update customerregister set password ='"+newPassword+"' where username='"+un+"' and answer='"+answer+"'"); //update data into table in database
               JOptionPane.showMessageDialog(null,"Your password is succefully updated");  //succes message
                int a = JOptionPane.showConfirmDialog(null, "Confirm Change?" , "Select",JOptionPane.YES_NO_OPTION);
                 if(a==0)
                 { 
                    setVisible(false);
                    new CustomerLogin().setVisible(true);
                 }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please write correct Password or Answer"); //failed message
             
            }
            
        }catch (ClassNotFoundException | SQLException e)
        {
           JOptionPane.showMessageDialog(null, e); 
        }      
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
        this.setVisible(false);
         new CustomerLogin().setVisible(true);
    }//GEN-LAST:event_myButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jUsername;
    private Project.MyButton myButton1;
    private Project.MyButton myButton2;
    private Project.MyButton myButton3;
    // End of variables declaration//GEN-END:variables
}
