package OOP;
//iman
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Clock;
import java.util.*;
import java.util.Timer;
import java.util.Date;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;


public class UserHome extends javax.swing.JFrame {
//date and time code
    int timeRun = 0;
    String username;
    private String un;
 
    public UserHome() {
        initComponents();
        
          new Thread()
          {
              public void run()
              {
                  while (true)
                  {
                      DateFormat date = new SimpleDateFormat("hh : mm : ss aa");
                      String datestring = date.format(new Date()).toString();
                      
                      jtime.setText(datestring);
                      
                      try
                      {
                        Thread.sleep(1);  
                      }
                      catch(Exception e)
                      {
                          
                      }
                  }
              }
                     
          }.start();
          dt();
         this.setLocationRelativeTo(null); //set frame center screen
    }
    public void dt()
    {
        Date d = new Date();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        
        String dd = sdf.format(d);
        jdate.setText(dd);
    }
    
    //get data username from CustomerLogin
    UserHome(String username)
    {
        this();
       this.username = username;
        welcome.setText("Welcome "+username+ " to UTHM Guesthouse Reservation. Have a nice day"); //get username
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcome = new javax.swing.JLabel();
        myButton3 = new Project.MyButton();
        myButton1 = new Project.MyButton();
        myButton2 = new Project.MyButton();
        jLabel6 = new javax.swing.JLabel();
        jdate = new javax.swing.JLabel();
        jtime = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 255, 255));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 900, 130));

        myButton3.setText("Log out");
        myButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 630, 130, 50));

        myButton1.setText("Book");
        myButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 130, 50));

        myButton2.setText("MyReservation");
        myButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(myButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 130, 50));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("What you want to do today?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 260, 50));

        jdate.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jdate.setForeground(new java.awt.Color(255, 255, 255));
        jdate.setText("0");
        getContentPane().add(jdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 340, 40));

        jtime.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jtime.setForeground(new java.awt.Color(255, 255, 255));
        jtime.setText("0");
        getContentPane().add(jtime, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 420, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Time :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 150, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 140, 50));

        jLabel5.setBackground(new java.awt.Color(0, 255, 204));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 670, 190));

        jLabel2.setBackground(new java.awt.Color(55, 71, 79));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 720));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton2ActionPerformed
                new UserViewBook(username).setVisible(true); // pass username to home
                this.setVisible(false);        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_myButton2ActionPerformed

    private void myButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1ActionPerformed
                new UserBook(username).setVisible(true); // pass username to home
                this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_myButton1ActionPerformed

    private void myButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton3ActionPerformed
       //confirm log out
        int a = JOptionPane.showConfirmDialog(null, "Are you want to log out?" , "Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
        this.setVisible(false);
        new CustomerLogin().setVisible(true);
        }
    }//GEN-LAST:event_myButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jtime;
    private Project.MyButton myButton1;
    private Project.MyButton myButton2;
    private Project.MyButton myButton3;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
